/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  javascriptSidebar: [{ type: 'autogenerated', dirName: 'javascript' }],
  typescriptSidebar: [{ type: 'autogenerated', dirName: 'typescript' }],
  reactSidebar: [{ type: 'autogenerated', dirName: 'react' }],
  nextJsSidebar: [{ type: 'autogenerated', dirName: 'nextjs' }],
  electronSidebar: [{ type: 'autogenerated', dirName: 'electron' }],
  jestSidebar: [{ type: 'autogenerated', dirName: 'jest' }],
  cypressSidebar: [{ type: 'autogenerated', dirName: 'cypress' }],
  playwrightSidebar: [{ type: 'autogenerated', dirName: 'playwright' }],
  zustandSidebar: [{ type: 'autogenerated', dirName: 'zustand' }],
  tanstackQuerySidebar: [{ type: 'autogenerated', dirName: 'tanstack-query' }],
  nextAuthJsSidebar: [{ type: 'autogenerated', dirName: 'nextauthjs' }],
  vanillaExtractSidebar: [
    { type: 'autogenerated', dirName: 'vanilla-extract' },
  ],
  tailwindCSSSidebar: [{ type: 'autogenerated', dirName: 'tailwind-css' }],
  chakraUISidebar: [{ type: 'autogenerated', dirName: 'chakra-ui' }],
  prismaSidebar: [{ type: 'autogenerated', dirName: 'prisma' }],
  docusaurusSidebar: [{ type: 'autogenerated', dirName: 'docusaurus' }],
  emmetSidebar: [{ type: 'autogenerated', dirName: 'emmet' }],
  regularExpressionSidebar: [
    { type: 'autogenerated', dirName: 'regular-expression' },
  ],
  yupSidebar: [{ type: 'autogenerated', dirName: 'yup' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
