/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'next-js/README',
    'next-js/시작하기',
    {
      문서: [
        {
          '기본 개념': [
            { type: 'autogenerated', dirName: 'next-js/문서/기본-개념' },
          ],
        },
        {
          '기본 기능': [
            {
              '데이터 가져오기': [
                {
                  type: 'autogenerated',
                  dirName: 'next-js/문서/기본-기능/데이터-가져오기',
                },
              ],
            },
          ],
        },
      ],
    },
    'next-js/트러블슈팅',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
